// Convert the menu items to work with Inertia.js routes
export const menuItems = [
  {
    id: "menu",
    label: "Menu",
    isHeader: true,
  },
  {
    id: "dashboard",
    label: "Dashboards",
    icon: "bx bx-home-circle",
    link: "#",
    subItems: [
      {
        id: "dashboard-default",
        label: "Default",
        link: "/admin/dashboard",
        parentId: "dashboard",
      },
      {
        id: "dashboard-saas",
        label: "Saas",
        link: "/admin/dashboard/saas",
        parentId: "dashboard",
      },
      {
        id: "dashboard-crypto",
        label: "Crypto",
        link: "/admin/dashboard/crypto",
        parentId: "dashboard",
      },
      {
        id: "dashboard-blog",
        label: "Blog",
        link: "/admin/dashboard/blog",
        parentId: "dashboard",
      },
      {
        id: "dashboard-job",
        label: "Job",
        link: "/admin/dashboard/job",
        parentId: "dashboard",
      },
    ],
  },
  {
    id: "apps",
    label: "Apps",
    isHeader: true,
  },
  {
    id: "calendar",
    label: "Calendar",
    icon: "bx bx-calendar",
    link: "/admin/calendar",
  },
  {
    id: "chat",
    label: "Chat",
    icon: "bx bx-chat",
    link: "/admin/chat",
  },
  {
    id: "file-manager",
    label: "File Manager",
    icon: "bx bx-file",
    link: "/admin/file-manager",
  },
  {
    id: "users",
    label: "User Management",
    icon: "bx bxs-group",
    link: "#",
    subItems: [
      {
        id: "user-list",
        label: "Users List",
        link: "/admin/users",
        parentId: "users",
      },
      {
        id: "add-new-user",
        label: "Create User",
        link: "/admin/users/create",
        parentId: "users",
      },
      {
        id: "roles",
        label: "Roles & Permissions",
        link: "/admin/roles",
        parentId: "users",
      },
    ],
  },
  {
    id: "services",
    label: "Service Management",
    icon: "bx bx-briefcase",
    link: "#",
    subItems: [
      {
        id: "service-list",
        label: "Services List",
        link: "/admin/services",
        parentId: "services",
      },
      {
        id: "add-new-service",
        label: "Create Service",
        link: "/admin/services/create",
        parentId: "services",
      },
    ],
  },
  {
    id: "ecommerce",
    label: "Ecommerce",
    icon: "bx bx-store",
    link: "#",
    subItems: [
      {
        id: "products",
        label: "Products",
        link: "/admin/ecommerce/products",
        parentId: "ecommerce",
      },
      {
        id: "add-product",
        label: "Add Product",
        link: "/admin/ecommerce/products/create",
        parentId: "ecommerce",
      },
      {
        id: "orders",
        label: "Orders",
        link: "/admin/ecommerce/orders",
        parentId: "ecommerce",
      },
      {
        id: "customers",
        label: "Customers",
        link: "/admin/ecommerce/customers",
        parentId: "ecommerce",
      },
      {
        id: "categories",
        label: "Categories",
        link: "/admin/ecommerce/categories",
        parentId: "ecommerce",
      },
    ],
  },
  {
    id: "email",
    label: "Email",
    icon: "bx bx-envelope",
    link: "#",
    subItems: [
      {
        id: "inbox",
        label: "Inbox",
        link: "/admin/email/inbox",
        parentId: "email",
      },
      {
        id: "compose",
        label: "Compose",
        link: "/admin/email/compose",
        parentId: "email",
      },
      {
        id: "templates",
        label: "Templates",
        link: "#",
        parentId: "email",
        subItems: [
          {
            id: "basic-template",
            label: "Basic Action",
            link: "/admin/email/templates/basic",
            parentId: "templates",
          },
          {
            id: "alert-template",
            label: "Alert Email",
            link: "/admin/email/templates/alert",
            parentId: "templates",
          },
          {
            id: "billing-template",
            label: "Billing Email",
            link: "/admin/email/templates/billing",
            parentId: "templates",
          },
        ],
      },
    ],
  },
  {
    id: "invoices",
    label: "Invoices",
    icon: "bx bx-receipt",
    link: "#",
    subItems: [
      {
        id: "invoice-list",
        label: "Invoice List",
        link: "/admin/invoices",
        parentId: "invoices",
      },
      {
        id: "create-invoice",
        label: "Create Invoice",
        link: "/admin/invoices/create",
        parentId: "invoices",
      },
    ],
  },
  {
    id: "projects",
    label: "Projects",
    icon: "bx bx-briefcase-alt-2",
    link: "#",
    subItems: [
      {
        id: "project-list",
        label: "Projects List",
        link: "/admin/projects",
        parentId: "projects",
      },
      {
        id: "create-project",
        label: "Create Project",
        link: "/admin/projects/create",
        parentId: "projects",
      },
    ],
  },
  {
    id: "tasks",
    label: "Tasks",
    icon: "bx bx-task",
    link: "#",
    subItems: [
      {
        id: "task-list",
        label: "Task List",
        link: "/admin/tasks",
        parentId: "tasks",
      },
      {
        id: "task-kanban",
        label: "Tasks Kanban",
        link: "/admin/tasks/kanban",
        parentId: "tasks",
      },
      {
        id: "create-task",
        label: "Create Task",
        link: "/admin/tasks/create",
        parentId: "tasks",
      },
    ],
  },
  {
    id: "blog",
    label: "Blog",
    icon: "bx bxs-detail",
    link: "#",
    subItems: [
      {
        id: "blog-posts",
        label: "Blog Posts",
        link: "/admin/blog/posts",
        parentId: "blog",
      },
      {
        id: "create-post",
        label: "Create Post",
        link: "/admin/blog/posts/create",
        parentId: "blog",
      },
      {
        id: "blog-categories",
        label: "Categories",
        link: "/admin/blog/categories",
        parentId: "blog",
      },
    ],
  },
  {
    id: "settings",
    label: "Settings",
    isHeader: true,
  },
  {
    id: "general-settings",
    label: "Settings",
    icon: "bx bx-cog",
    link: "#",
    subItems: [
      {
        id: "general",
        label: "General Settings",
        link: "/admin/settings/general",
        parentId: "general-settings",
      },
      {
        id: "email-settings",
        label: "Email Settings",
        link: "/admin/settings/email",
        parentId: "general-settings",
      },
      {
        id: "notifications",
        label: "Notifications",
        link: "/admin/settings/notifications",
        parentId: "general-settings",
      },
      {
        id: "security",
        label: "Security",
        link: "/admin/settings/security",
        parentId: "general-settings",
      },
    ],
  },
  {
    id: "authentication",
    label: "Authentication",
    icon: "bx bx-user-circle",
    link: "#",
    subItems: [
      {
        id: "login",
        label: "Login",
        link: "/login",
        parentId: "authentication",
      },
      {
        id: "register",
        label: "Register",
        link: "/register",
        parentId: "authentication",
      },
      {
        id: "forgot-password",
        label: "Forgot Password",
        link: "/forgot-password",
        parentId: "authentication",
      },
      {
        id: "reset-password",
        label: "Reset Password",
        link: "/reset-password",
        parentId: "authentication",
      },
      {
        id: "email-verify",
        label: "Email Verification",
        link: "/email/verify",
        parentId: "authentication",
      },
      {
        id: "two-factor",
        label: "Two Factor Authentication",
        link: "/two-factor-challenge",
        parentId: "authentication",
      },
    ],
  },
  {
    id: "components",
    label: "Components",
    isHeader: true,
  },
  {
    id: "ui-elements",
    label: "UI Elements",
    icon: "bx bx-tone",
    link: "#",
    subItems: [
      {
        id: "alerts",
        label: "Alerts",
        link: "/admin/ui/alerts",
        parentId: "ui-elements",
      },
      {
        id: "buttons",
        label: "Buttons",
        link: "/admin/ui/buttons",
        parentId: "ui-elements",
      },
      {
        id: "cards",
        label: "Cards",
        link: "/admin/ui/cards",
        parentId: "ui-elements",
      },
      {
        id: "modals",
        label: "Modals",
        link: "/admin/ui/modals",
        parentId: "ui-elements",
      },
      {
        id: "tabs",
        label: "Tabs & Accordions",
        link: "/admin/ui/tabs",
        parentId: "ui-elements",
      },
      {
        id: "typography",
        label: "Typography",
        link: "/admin/ui/typography",
        parentId: "ui-elements",
      },
    ],
  },
  {
    id: "forms",
    label: "Forms",
    icon: "bx bxs-eraser",
    link: "#",
    subItems: [
      {
        id: "form-elements",
        label: "Form Elements",
        link: "/admin/forms/elements",
        parentId: "forms",
      },
      {
        id: "form-layouts",
        label: "Form Layouts",
        link: "/admin/forms/layouts",
        parentId: "forms",
      },
      {
        id: "form-validation",
        label: "Form Validation",
        link: "/admin/forms/validation",
        parentId: "forms",
      },
      {
        id: "form-advanced",
        label: "Form Advanced",
        link: "/admin/forms/advanced",
        parentId: "forms",
      },
      {
        id: "form-editors",
        label: "Form Editors",
        link: "/admin/forms/editors",
        parentId: "forms",
      },
      {
        id: "file-upload",
        label: "File Upload",
        link: "/admin/forms/upload",
        parentId: "forms",
      },
    ],
  },
  {
    id: "tables",
    label: "Tables",
    icon: "bx bx-list-ul",
    link: "#",
    subItems: [
      {
        id: "basic-tables",
        label: "Basic Tables",
        link: "/admin/tables/basic",
        parentId: "tables",
      },
      {
        id: "data-tables",
        label: "Data Tables",
        link: "/admin/tables/data",
        parentId: "tables",
      },
    ],
  },
  {
    id: "charts",
    label: "Charts",
    icon: "bx bxs-bar-chart-alt-2",
    link: "#",
    subItems: [
      {
        id: "apex-charts",
        label: "Apex Charts",
        link: "/admin/charts/apex",
        parentId: "charts",
      },
      {
        id: "chartjs",
        label: "Chart.js",
        link: "/admin/charts/chartjs",
        parentId: "charts",
      },
    ],
  },
  
]
